global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: 'fabric'
    # Retain labels
    honor_labels: true
    # Assumes local caliper workers are scrape targets, only one here
    static_configs:
    - targets: ['peer0.org1.example.com:9443', 'peer0.org2.example.com:9443']
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: caliper
    scrape_interval: 5s
    static_configs:
    # assume single local caliper worker here, exposed on port 3000.
    # host.docker.internal if on mac
    # localhost otherwise
    - targets: ['localhost:3001', 'localhost:3002', 'localhost:3003', 'localhost:3004', 'localhost:3005' ]
